import React, { useMemo, useState, useEffect } from 'react';
import * as anchor from '@coral-xyz/anchor';
import { Connection, PublicKey, SystemProgram, clusterApiUrl, Keypair } from '@solana/web3.js';
import idl from './idl/pop_profiles.json';

// Basic Phantom-only wallet connector (no wallet-adapter to keep deps light)
// We gracefully degrade if window.solana is not available

declare global {
  interface Window { solana?: any }
}

// A dummy wallet to initialize the Anchor provider, since we build and sign
// transactions manually.
class DummyWallet {
  constructor(readonly payer: Keypair) {}

  async signTransaction(tx: anchor.web3.Transaction): Promise<anchor.web3.Transaction> {
    tx.partialSign(this.payer);
    return tx;
  }

  async signAllTransactions(txs: anchor.web3.Transaction[]): Promise<anchor.web3.Transaction[]> {
    return txs.map((t) => {
      t.partialSign(this.payer);
      return t;
    });
  }

  get publicKey(): PublicKey {
    return this.payer.publicKey;
  }
}

const PROGRAM_ID = new PublicKey(import.meta.env.VITE_PROGRAM_ID || (idl as any).address || 'PopPro111111111111111111111111111111111111111');
const CLUSTER = (import.meta.env.VITE_CLUSTER || 'devnet') as 'devnet' | 'localnet' | 'local';

function useConnection() {
  const endpoint = CLUSTER === 'devnet' ? clusterApiUrl('devnet') : 'http://127.0.0.1:8899';
  const conn = useMemo(() => new Connection(endpoint, 'confirmed'), [endpoint]);
  return conn;
}

function useAnchorProgram(walletPubkey: PublicKey | null) {
  const connection = useConnection();
  const provider = useMemo(() => {
    // A dummy wallet is used to initialize the provider, as we will be signing
    // transactions manually.
    const dummy = new DummyWallet(Keypair.generate());
    return new anchor.AnchorProvider(connection, dummy, anchor.AnchorProvider.defaultOptions());
  }, [connection]);

  const program = useMemo(() => {
    // The IDL generated by modern Anchor CLI versions has a different format
    // for the `accounts` section than what some versions of the Anchor JS
    // library expect. This can cause errors like `coder.accounts is undefined`.
    // To fix this, we transform the IDL in-memory to the older format before
    // passing it to the Program constructor.
    // We also handle the case where the IDL is wrapped in a `default` object.
    const rawIdl = idl.default || idl;
    const idlCopy: any = JSON.parse(JSON.stringify(rawIdl));

    if (idlCopy.accounts && idlCopy.types) {
      // Create a map of type definitions for quick lookup.
      const typesMap = new Map(idlCopy.types.map((t: any) => [t.name, t]));
      // Replace the "stub" account definitions with the full definitions
      // from the `types` array, which is what older Anchor JS versions expect.
      idlCopy.accounts = idlCopy.accounts.map((acc: { name: string }) => {
        const typeDef = typesMap.get(acc.name);
        return typeDef ? { name: typeDef.name, type: typeDef.type } : acc;
      });
    }

    return new anchor.Program(idlCopy as anchor.Idl, PROGRAM_ID, provider);
  }, [provider]);
  return program;
}

function short(pk?: PublicKey | string) {
  const s = typeof pk === 'string' ? pk : pk?.toBase58();
  return s ? s.slice(0, 4) + '…' + s.slice(-4) : '';
}

export default function App() {
  const connection = useConnection();
  const [wallet, setWallet] = useState<any>(null);
  const [pubkey, setPubkey] = useState<PublicKey | null>(null);
  const program = useAnchorProgram(pubkey);

  const [username, setUsername] = useState('alice');
  const [bio, setBio] = useState('solana freelancer');
  const [profilePda, setProfilePda] = useState<PublicKey | null>(null);
  const [profile, setProfile] = useState<any | null>(null);
  const [certs, setCerts] = useState<any[]>([]);

  const [certTitle, setCertTitle] = useState('DeFi Project');
  const [certUri, setCertUri] = useState('https://example.com/work/123');

  const [endorseeOwner, setEndorseeOwner] = useState('');
  const [feedback, setFeedback] = useState('Great work!');
  const [rating, setRating] = useState(5);

  const [busy, setBusy] = useState<string>('');
  const [message, setMessage] = useState<string>('');

  // Connect Phantom
  const connect = async () => {
    try {
      if (!window.solana || !window.solana.isPhantom) {
        window.open('https://phantom.app/', '_blank');
        return;
      }
      const resp = await window.solana.connect();
      setWallet(window.solana);
      setPubkey(new PublicKey(resp.publicKey));
    } catch (e: any) {
      setMessage(e.message || String(e));
    }
  };

  const disconnect = async () => {
    try { await wallet?.disconnect?.(); } catch {}
    setWallet(null); setPubkey(null); setProfile(null); setCerts([]); setProfilePda(null);
  };

  // Derive profile PDA when pubkey changes
  useEffect(() => {
    if (!pubkey) { setProfilePda(null); return; }
    const [pda] = PublicKey.findProgramAddressSync([Buffer.from('profile'), pubkey.toBuffer()], PROGRAM_ID);
    setProfilePda(pda);
  }, [pubkey]);

  // Fetch profile + certs
  const refresh = async () => {
    if (!profilePda) return;
    try {
      const p = await (program.account as any).userProfile.fetch(profilePda);
      setProfile(p);
      const count = (p.certCount?.toNumber ? p.certCount.toNumber() : p.certCount) as number;
      const list: any[] = [];
      for (let i = 0; i < count; i++) {
        const [cAddr] = PublicKey.findProgramAddressSync([
          Buffer.from('cert'), profilePda.toBuffer(), new anchor.BN(i).toArrayLike(Buffer, 'le', 4)
        ], PROGRAM_ID);
        try { const c = await (program.account as any).certification.fetch(cAddr); list.push(c); } catch {}
      }
      setCerts(list);
    } catch (_e) {
      setProfile(null); setCerts([]);
    }
  };

  useEffect(() => { refresh(); }, [profilePda]);

  // Helper to send Anchor methods using Phantom
  async function sendIx(ix: anchor.web3.TransactionInstruction, signers: PublicKey[], commitment: anchor.web3.Finality = 'confirmed') {
    if (!wallet || !pubkey) throw new Error('Connect wallet');
    const tx = new anchor.web3.Transaction().add(ix);
    tx.feePayer = pubkey;
    tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;
    const signed = await wallet.signTransaction(tx);
    const sig = await connection.sendRawTransaction(signed.serialize());
    await connection.confirmTransaction({ signature: sig, ...(await connection.getLatestBlockhash()) }, commitment);
    return sig;
  }

  const onCreateProfile = async () => {
    if (!pubkey || !profilePda) return;
    try {
      setBusy('Creating profile…'); setMessage('');
      const ix = await program.methods.createUserProfile(username, bio)
        .accounts({ authority: pubkey, profile: profilePda, systemProgram: SystemProgram.programId })
        .instruction();
      const sig = await sendIx(ix, [pubkey]);
      setMessage(`Profile created: ${sig}`);
      await refresh();
    } catch (e: any) {
      setMessage(e.message || String(e));
    } finally { setBusy(''); }
  };

  const onAddCert = async () => {
    if (!pubkey || !profilePda || !profile) return;
    try {
      setBusy('Adding certification…'); setMessage('');
      const ix = await program.methods.addCertification(certTitle, certUri, pubkey)
        .accounts({ authority: pubkey, profile: profilePda, certification: PublicKey.findProgramAddressSync([
          Buffer.from('cert'), profilePda.toBuffer(), new anchor.BN(profile.certCount).toArrayLike(Buffer, 'le', 4)
        ], PROGRAM_ID)[0], systemProgram: SystemProgram.programId })
        .instruction();
      const sig = await sendIx(ix, [pubkey]);
      setMessage(`Certification added: ${sig}`);
      await refresh();
    } catch (e: any) {
      setMessage(e.message || String(e));
    } finally { setBusy(''); }
  };

  const onEndorse = async () => {
    if (!pubkey) return;
    try {
      const owner = new PublicKey(endorseeOwner);
      const [pda] = PublicKey.findProgramAddressSync([Buffer.from('profile'), owner.toBuffer()], PROGRAM_ID);
      const latest = await (program.account as any).userProfile.fetch(pda);
      const [endorsement] = PublicKey.findProgramAddressSync([
        Buffer.from('endorsement'), pda.toBuffer(), pubkey.toBuffer(), new anchor.BN(latest.endorsementCount).toArrayLike(Buffer, 'le', 4)
      ], PROGRAM_ID);

      setBusy('Sending endorsement…'); setMessage('');
      const ix = await program.methods.endorseUser(feedback, rating)
        .accounts({ endorser: pubkey, profile: pda, endorsement, systemProgram: SystemProgram.programId })
        .instruction();
      const sig = await sendIx(ix, [pubkey]);
      setMessage(`Endorsed: ${sig}`);
      if (profilePda && pda.equals(profilePda)) await refresh();
    } catch (e: any) {
      setMessage(e.message || String(e));
    } finally { setBusy(''); }
  };

  return (
    <div className="container">
      <header>
        <h1>Pop Profiles</h1>
        <div className="row">
          <select value={CLUSTER} disabled>
            <option value="devnet">devnet</option>
            <option value="localnet">localnet</option>
          </select>
          {pubkey ? (
            <button onClick={disconnect}>Disconnect {short(pubkey)}</button>
          ) : (
            <button className="primary" onClick={connect}>Connect Phantom</button>
          )}
        </div>
      </header>

      <div className="card">
        <div className="row" style={{justifyContent:'space-between'}}>
          <div>
            <div className="muted">Program</div>
            <div className="mono">{PROGRAM_ID.toBase58()}</div>
          </div>
          <div>
            <div className="muted">Wallet</div>
            <div className="mono">{pubkey ? pubkey.toBase58() : 'not connected'}</div>
          </div>
        </div>
      </div>

      <div className="card">
        <h3>Your Profile</h3>
        {profile ? (
          <>
            <div className="row"><strong>Username:</strong> {profile.username}</div>
            <div className="row"><strong>Bio:</strong> {profile.bio}</div>
            <div className="row"><strong>Certifications:</strong> {profile.certCount?.toString?.() ?? String(profile.certCount)}</div>
            <div className="row"><strong>Endorsements:</strong> {profile.endorsementCount?.toString?.() ?? String(profile.endorsementCount)}</div>
            <div style={{marginTop: '1.5rem'}}>
              <h4>Certifications</h4>
              <div className="list">
                {certs.length === 0 && <div className="muted">No certifications yet.</div>}
                {certs.map((c, i) => (
                  <div key={i} className="row" style={{justifyContent:'space-between'}}>
                    <div>
                      <div><strong>{c.title}</strong></div>
                      <div className="muted">{c.uri}</div>
                    </div>
                    <div className="muted">Issuer: {short(c.issuer)}</div>
                  </div>
                ))}
              </div>
            </div>
          </>
        ) : (
          <div className="muted">No profile found for the connected wallet.</div>
        )}

        <div style={{marginTop: '1.5rem'}} className="row">
          <input className="flex-grow" placeholder="username" value={username} onChange={e=>setUsername(e.target.value)} />
          <input className="flex-grow" placeholder="bio" value={bio} onChange={e=>setBio(e.target.value)} />
          <button className="primary" disabled={!pubkey || !!busy} onClick={onCreateProfile}>Create / Update Profile</button>
          <button onClick={refresh}>Refresh</button>
        </div>
      </div>

      <div className="card">
        <h3>Add Certification</h3>
        <div className="row">
          <input className="flex-grow" placeholder="title" value={certTitle} onChange={e=>setCertTitle(e.target.value)} />
          <input className="flex-grow" placeholder="uri" value={certUri} onChange={e=>setCertUri(e.target.value)} />
          <button className="primary" disabled={!profile || !pubkey || !!busy} onClick={onAddCert}>Add</button>
        </div>
        <div className="muted">Only the profile owner can add certifications.</div>
      </div>

      <div className="card">
        <h3>Endorse Someone</h3>
        <div className="row">
          <input className="flex-grow" placeholder="profile owner pubkey" value={endorseeOwner} onChange={e=>setEndorseeOwner(e.target.value)} />
          <input placeholder="feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} />
          <input type="number" min={0} max={5} value={rating} onChange={e=>setRating(Number(e.target.value))} />
          <button className="primary" disabled={!pubkey || !!busy} onClick={onEndorse}>Endorse</button>
        </div>
        <div className="muted">You cannot endorse yourself. Rating 0-5.</div>
      </div>

      {busy && <div className="message-card info">{busy}</div>}
      {message && <div className="message-card error">{message}</div>}

      <div className="card">
        <div className="muted">Tip: Finding all endorsements requires indexing program accounts filtered by the profile field.</div>
      </div>
    </div>
  );
}